FROM debian:trixie-slim@sha256:a29215f6a35e51e22adffa17f89e9d2ef06214e64a2bad10d765c46aea49f11f
RUN apt-get update -qq \
    && apt-get install -yqq --no-install-recommends librsvg2-bin fontconfig \
    && rm -rf /var/lib/apt/lists/*
