[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"

[buildPlans.iosevka-custom.variants.design]
nine = "open-contour"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
zero = "dotted"
asterisk = "hexlow"
m = "shortleg"
percent = "dots"
 
###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
[buildPlans.iosevka-custom.weights.light]
shape = 200
menu  = 300
css   = 300

[buildPlans.iosevka-custom.weights.regular]
shape = 300
menu  = 400
css   = 400

[buildPlans.iosevka-custom.weights.medium]
shape = 400
menu  = 500
css   = 500

[buildPlans.iosevka-custom.weights.bold]
shape = 500
menu  = 700
css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.

[buildPlans.iosevka-custom.slants]
upright = "normal"
# italic = "italic"
# oblique = "oblique"

# End slant section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports integers between 3 and 9 (inclusive), while
#             "menu" only supports integers between 1 and 9 (inclusive).
#             If you decide to use custom widths you have to define all the widths you
#             plan to use otherwise they will not be built.

[buildPlans.iosevka-custom.widths.normal]
shape = 540        # Width grade of glyph shapes. NOT actual character width.
menu  = 5          # Width grade for the font's names. NOT actual character width.
css   = "normal"   # "font-stretch' property of webfont CSS.

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

# [buildPlans.iosevka-custom.metric-override]
# leading = 1250
# winMetricAscenderPad = 0
# winMetricDescenderPad = 0
# powerlineScaleY = 1
# powerlineScaleX = 1
# powerlineShiftY = 0
# powerlineShiftX = 0

# End metric override section
###################################################################################################
